---
- hosts: localhost
  connection: localhost
  gather_facts: no
  vars_files:
    - "{{ cluster_name }}/services/{{ service_name }}/common.yml"                 # include common variables
    - "{{ cluster_name }}/services/{{ service_name }}/{{ env }}.yml"              # include environment specific variables
  roles:
    - role: roles/aws.ec2-loadbalancer                  # create the load balancer for the service if needed
      when: elb_create | default(false)
    - role: roles/aws.ecs-ecr                           # create an ECR repository if needed
      when: ecr_create | default(false)
    - role: roles/aws.ecs-service                         # create the ecs service
      ecs_load_balancers: "{{ [elb_output_load_balancer] }}" # this variable is extracted from the load balancer modules
