---
# vars file for ansible-infra.aws-asg

# Launch config related
# http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html
asg_launch_config_amis_per_region:
  us-east-1:	"ami-0e297018"
  us-east-2:	"ami-43d0f626"
  us-west-1:	"ami-fcd7f59c"
  us-west-2:	"ami-596d6520"
  eu-west-1:	"ami-5ae4f83c"
  eu-west-2:	"ami-ada6b1c9"
  eu-central-1:	"ami-25a4004a"
  ap-northeast-1:	"ami-3a000e5d"
  ap-southeast-1:	"ami-2428ab47"
  ap-southeast-2:	"ami-ac5849cf"
  ca-central-1:	"ami-8cfb44e8"

asg_tag_name:
  Name: "{{ asg_ecs_cluster_name }}"
  propagate_at_launch: true

asg_tags: "{{ asg_additional_tags + [ asg_tag_name ] }}"
