---
# vars file for ansible-infra.aws-asg

# Launch config related
# http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html
asg_launch_config_amis_per_region:
  ap-southeast-2:   "ami-5781be34"
  ap-southeast-1:   "ami-a900a3ca"
  ap-northeast-1:   "ami-9cd57ffd"
  eu-central-1:     "ami-54f5303b"
  us-east-1:        "ami-eca289fb"
  us-east-2:        "ami-446f3521"
  us-west-1:        "ami-9fadf8ff"
  us-west-2:        "ami-7abc111a"
  eu-west-1:        "ami-a1491ad2"

asg_tag_name:
  Name: "{{ asg_ecs_cluster_name }}"
  propagate_at_launch: true

asg_tags: "{{ asg_additional_tags + [ asg_tag_name ] }}"
