---
- name: Create Security group
  ec2_group:
    name: "{{ sg_cluster_name }}-cluster"
    description: "{{ sg_description }}"
    state: "{{ sg_state }}"
    region: "{{ aws_region }}"
    profile: "{{ aws_profile }}"
    rules: "{{ sg_rules }}"
    purge_rules: "{{ sg_purge_rules }}"
    purge_rules_egress: "{{ sg_purge_rules_egress }}"
    vpc_id: "{{ sg_vpc_id }}"
  register: sg_info

- name: Tag security groups
  ec2_tag:
    resource: "{{ sg_info.group_id }}"
    region: "{{ sg_info.invocation.module_args.region | default(aws_region) }}"
    profile: "{{ sg_info.invocation.module_args.profile | default(aws_profile) }}"
    state: present
    tags:
      Name: "{{ sg_info.invocation.module_args.name }}"
      ClusterName: "{{ sg_cluster_name }}"
